### ISSUE TITLE
[feature] global config

### ISSUE THREAD

**Issue by krzysztof-kabala** [faja/yake#2]
`yake _config` can be a task displaying all config vars (so that default ones extended by local from file).

Moreover, there could be some file like `$HOME/.yakeconfig` where we can put `_config` section to be default values for yake.

And last part of this feature, if we type: `yake _config showcmd=false keepgoing=true`, global config will be updated.

**Comment by amsdard** [comment]
I see no use case for _$HOME/.yakeconfig_, In dozens of projects I was working on, there was never such a need. Local config is enough. Also _yake _config_ is pointless, you can do _cat yakefile_ to get the same.

**Comment by krzysztof-kabala** [comment]
> Also yake _config is pointless, you can do cat yakefile to get the same.

yake has global=default values for `_config`, `cat Yakefile` shows only local overwrites but no real values of each of them.

the only grounds for this feature implementation is posibility to see and set custom default values once

**Comment by faja** [comment]
To be clear, by `global` config you mean `_config` section in `$HOME/.yakeconfig`, and by `local` config you mean `_config` section in `Yakefile`?

[edit]
Going further with this, could `$HOME/yakeconfig` include `tasks` as well? If so it means merging variables, merging steps, and in the end it could become unclear where all the steps/vars come from.

I would stick with simple `Yakefile` where you can define steps and variables and that's it, KISS.

Having one or two variables duplicated in `_config` section in multiple `Yakefile`s is not that bad, and makes things easier to read and understand:)

**Comment by krzysztof-kabala** [comment]
> To be clear, by global config you mean _config section in $HOME/.yakeconfig, and by local config you mean _config section in Yakefile?

correct, "global" config neednt be a file, can be any kind of system storage to keep default values.

the idea of this feature is to overwrite hardcoded config values here: https://github.com/faja/yake/blob/master/main.go#L32
`flagShowcmd := flag.Bool("showcmd", true, "prints executed command")`

by default i want: 

```
flagKeepgoing=true
flagStdout=true
flagStderr=true
flagShowcmd=false
```

and thats all :)

**Comment by faja** [comment]
Since such values make more sens to you guys, I've just updated them: https://github.com/faja/yake/blob/master/main.go#L29-L32

**Comment by faja** [comment]
Are you happy to close this issue?

**Comment by krzysztof-kabala** [comment]
yes, can be closed, works perfectly now! :)
