### ISSUE TITLE
[feature] bash-completion

### ISSUE THREAD

**Issue by krzysztof-kabala** [faja/yake#3]
https://github.com/urfave/cli#bash-completion

as "cool to have but not important/reqired" feature, I suggest adding sthg like bash completion:
`yake co[tab key]` -> `yake console`

but only if its quick to implement, its really not-important

**Comment by faja** [comment]
Autocompletion is your shell feature. I've added `extras/yake_completion.bash`. Simply source it `. extras/yake_completion.bash`, or add it to your `/etc/bash_completion.d` directory.

It should do the trick.

**Comment by faja** [comment]
eg:

```
[mc@mc yake]$ ./yake <tab> <tab>
_config  test     test2    test3    
[mc@mc yake]$ ./yake -file examples/yakefile.yml <tab> <tab>
_config              simple_task          task_with_CMD        task_with_variables
```

**Comment by krzysztof-kabala** [comment]
works perfectly :) thanks
